-- Sample Recovery Notes with Realistic US Healthcare Data
INSERT INTO clinical_notes (id, patient_id, practitioner_id, appointment_id, title, subjective, objective, assessment, plan, created_at, updated_at) VALUES
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%johnson%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  NULL,
  'Annual Physical Examination',
  'Patient reports feeling well overall. No acute complaints. Has been maintaining regular exercise routine of walking 30 minutes daily. Diet consists of balanced meals with minimal processed foods. Sleep pattern is regular, 7-8 hours nightly. Denies tobacco use, alcohol consumption limited to 1-2 glasses of wine weekly. Current medications: Lisinopril 10mg daily for hypertension, Metformin 500mg twice daily for type 2 diabetes. Reports good adherence to medications.',
  'Vital Signs: BP 128/82 mmHg, HR 72 bpm, RR 16, Temp 98.4°F, O2 Sat 98% on room air, Weight 165 lbs, Height 5''6", BMI 26.6. General: Alert, oriented, well-appearing female in no acute distress. HEENT: Normocephalic, atraumatic. PERRLA. TMs clear bilaterally. Throat non-erythematous. Cardiovascular: Regular rate and rhythm, no murmurs. Pulmonary: Clear to auscultation bilaterally. Abdomen: Soft, non-tender, non-distended, bowel sounds present. Extremities: No edema, good pulses. Skin: No suspicious lesions noted.',
  'Hypertension - well controlled on current medication. Type 2 Diabetes Mellitus - good glycemic control based on recent HbA1c of 6.8%. Overweight - BMI 26.6, patient motivated for weight management.',
  '1. Continue Lisinopril 10mg daily, check BP in 3 months\n2. Continue Metformin, order HbA1c and comprehensive metabolic panel in 3 months\n3. Dietary counseling provided for weight management\n4. Mammogram due - order bilateral screening mammogram\n5. Colonoscopy due at age 50 - discussed screening options\n6. Return in 6 months for routine follow-up',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%smith%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  NULL,
  'Upper Respiratory Infection',
  'Patient presents with 3-day history of nasal congestion, sore throat, and low-grade fever. Reports maximum temperature of 100.2°F at home. Mild headache and body aches. Denies shortness of breath, chest pain, or productive cough. No recent travel or known COVID-19 exposure. Has been taking over-the-counter acetaminophen and using saline nasal spray with minimal relief.',
  'Vital Signs: BP 118/76 mmHg, HR 88 bpm, RR 18, Temp 99.8°F, O2 Sat 97% on room air. General: Appears mildly ill but in no acute distress. HEENT: Nasal congestion with clear discharge, erythematous posterior pharynx without exudate, no lymphadenopathy. Cardiovascular: Regular rate and rhythm. Pulmonary: Clear to auscultation, no wheezes or crackles. Rapid strep test: Negative.',
  'Viral upper respiratory infection (common cold). No evidence of bacterial infection.',
  '1. Supportive care with rest and increased fluid intake\n2. Continue acetaminophen 650mg every 6 hours as needed for fever/discomfort\n3. Saline nasal rinses twice daily\n4. Throat lozenges for sore throat\n5. Return if symptoms worsen or persist beyond 7-10 days\n6. Return immediately if develops shortness of breath, chest pain, or high fever >101.5°F',
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%williams%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  NULL,
  'Anxiety Depression Follow-up',
  'Follow-up for anxiety and depression management',
  'Patient returns for follow-up of generalized anxiety disorder and major depressive disorder. Started sertraline 50mg daily 6 weeks ago. Reports significant improvement in mood and anxiety levels. Sleep has improved from 4-5 hours to 6-7 hours nightly. Appetite has returned to normal. Denies suicidal ideation. Still experiences occasional panic episodes but frequency has decreased from daily to 2-3 times per week. Participating in cognitive behavioral therapy weekly.',
  'Vital Signs: BP 122/78 mmHg, HR 76 bpm, Weight 158 lbs (gained 3 lbs since last visit). Mental Status: Alert, cooperative, appropriate affect. PHQ-9 score: 8 (down from 16 at last visit). GAD-7 score: 9 (down from 18 at last visit). No evidence of psychosis or thought disorder.',
  'Generalized anxiety disorder - improving on sertraline therapy. Major depressive disorder - significant improvement with current treatment regimen.',
  '1. Continue sertraline 50mg daily - patient tolerating well\n2. Continue weekly CBT sessions\n3. Encouraged regular exercise and stress management techniques\n4. Follow-up in 4 weeks to assess continued improvement\n5. Patient provided with crisis contact information\n6. Discussed importance of medication compliance',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '3 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%brown%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  NULL,
  'Chronic Back Pain Evaluation',
  'Chronic low back pain evaluation',
  'Patient referred by primary care for evaluation of chronic low back pain present for 8 months. Pain is described as aching, 6/10 severity, worse with prolonged sitting and bending forward. Some relief with walking and lying down. Denies radiation to legs, numbness, or weakness. Has tried NSAIDs, physical therapy for 6 weeks with minimal improvement. Works as an office manager, sits at desk 8 hours daily. No history of trauma or injury.',
  'Vital Signs: BP 134/86 mmHg, HR 74 bpm, Weight 185 lbs. Musculoskeletal: Limited forward flexion to 45 degrees, negative straight leg raise bilaterally, no focal neurologic deficits. Lumbar spine tenderness over L4-L5 region. Gait normal. MRI lumbar spine shows mild degenerative disc disease at L4-L5 with small central disc protrusion, no nerve compression.',
  'Chronic mechanical low back pain secondary to degenerative disc disease L4-L5 with disc protrusion. No evidence of nerve root compression or cauda equina syndrome.',
  '1. Recommend ergonomic workstation evaluation\n2. Prescribe gabapentin 300mg three times daily for neuropathic component\n3. Continue physical therapy focusing on core strengthening\n4. Consider epidural steroid injection if no improvement in 4 weeks\n5. Work restriction: no lifting >20 lbs, frequent position changes\n6. Follow-up in 4 weeks',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '5 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%davis%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  NULL,
  'routine_visit',
  'Pediatric well-child examination - 5 year old',
  'Parent reports child is doing well overall. Eating variety of foods, growth appropriate. Sleeping 10-11 hours nightly without issues. Toilet trained, no accidents. Starting kindergarten next month. Up to date with speech and language development. No behavioral concerns. No recent illnesses or injuries.',
  'Vital Signs: Height 42 inches (50th percentile), Weight 40 lbs (45th percentile), BMI 16.2 (normal), BP 95/60 mmHg, HR 100 bpm, Temp 98.6°F. General: Well-appearing, interactive child in no distress. HEENT: Normocephalic, PERRLA, TMs clear, throat non-erythematous. Cardiovascular: Regular rate, no murmurs. Pulmonary: Clear bilaterally. Abdomen: Soft, non-tender. Development: Age-appropriate language skills, follows multi-step commands, draws person with 6 body parts.',
  'Healthy 5-year-old with normal growth and development. Ready for kindergarten entry.',
  '1. Administer DTaP, IPV, and MMR vaccines today\n2. Vision and hearing screening - both normal\n3. Discussed kindergarten readiness, safety measures\n4. Reviewed proper nutrition and physical activity\n5. Dental care - recommend first dental visit if not already done\n6. Next well-child visit at age 6\n7. Provided anticipatory guidance for school-age development',
  NOW() - INTERVAL '1 week',
  NOW() - INTERVAL '1 week'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%miller%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  NULL,
  'urgent_care',
  'Suspected urinary tract infection',
  'Patient presents with 2-day history of dysuria, urinary frequency, and urgency. Reports burning sensation with urination and feeling of incomplete emptying. Denies fever, chills, back pain, or nausea. Last UTI was 8 months ago, treated successfully with antibiotics. Sexually active, monogamous relationship. Uses birth control pills.',
  'Vital Signs: BP 118/72 mmHg, HR 84 bpm, Temp 98.8°F. General: Appears comfortable, no acute distress. Abdomen: Mild suprapubic tenderness, no CVA tenderness. Urinalysis: Positive leukocyte esterase, positive nitrites, >50 WBCs/hpf, moderate bacteria, no RBCs or casts.',
  'Uncomplicated urinary tract infection, likely cystitis.',
  '1. Prescribed nitrofurantoin 100mg twice daily for 5 days\n2. Increase fluid intake, cranberry juice may be beneficial\n3. Avoid irritants (caffeine, alcohol, spicy foods)\n4. Complete entire antibiotic course even if symptoms improve\n5. Return if symptoms worsen or persist after 48 hours of treatment\n6. Consider urology referral if recurrent UTIs (>3 in 12 months)',
  NOW() - INTERVAL '4 hours',
  NOW() - INTERVAL '4 hours'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%wilson%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  NULL,
  'Anxiety Depression Follow-up',
  'Hypertension and hyperlipidemia management',
  'Patient returns for routine follow-up of hypertension and hyperlipidemia. Currently taking amlodipine 5mg daily and atorvastatin 20mg at bedtime. Reports good medication compliance. Home blood pressure readings average 135/85 mmHg. Denies chest pain, shortness of breath, or edema. Following Mediterranean diet and walking 4 times weekly for 45 minutes.',
  'Vital Signs: BP 138/86 mmHg (repeat: 134/84 mmHg), HR 68 bpm, Weight 178 lbs (lost 4 lbs since last visit). Cardiovascular: Regular rate and rhythm, no murmurs. Recent labs: Total cholesterol 185 mg/dL, LDL 110 mg/dL, HDL 45 mg/dL, Triglycerides 150 mg/dL, HbA1c 5.8%.',
  'Hypertension - not at goal, consider medication adjustment. Hyperlipidemia - improved but LDL still above target for cardiovascular risk reduction.',
  '1. Increase amlodipine to 10mg daily\n2. Continue atorvastatin 20mg, recheck lipid panel in 6 weeks\n3. Consider adding ACE inhibitor if BP not controlled in 4 weeks\n4. Continue current lifestyle modifications\n5. Home BP monitoring - target <130/80 mmHg\n6. Return in 4 weeks for BP check',
  NOW() - INTERVAL '6 days',
  NOW() - INTERVAL '6 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%moore%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  NULL,
  'sick_visit',
  'Acute migraine headache',
  'Patient presents with severe left-sided throbbing headache that started 4 hours ago. Associated with nausea, vomiting (2 episodes), and photophobia. Reports this is similar to previous migraines but more severe than usual. Tried acetaminophen and ibuprofen at home without relief. Denies fever, neck stiffness, or visual changes. Last migraine was 3 months ago.',
  'Vital Signs: BP 142/88 mmHg, HR 92 bpm, Temp 98.4°F. Neurologic: Alert and oriented, photophobic, mild neck tension but no nuchal rigidity. Cranial nerves II-XII intact. No focal motor or sensory deficits. Fundoscopic exam: no papilledema.',
  'Acute migraine headache without aura. No evidence of secondary headache disorder.',
  '1. Administer sumatriptan 6mg subcutaneous injection\n2. IV fluids 500mL normal saline for dehydration\n3. Ondansetron 4mg IV for nausea\n4. Prescribed sumatriptan 50mg tablets for home use\n5. Dark, quiet environment for recovery\n6. Follow-up with primary care if increasing frequency of migraines\n7. Return immediately if develops fever, neck stiffness, or neurologic symptoms',
  NOW() - INTERVAL '2 hours',
  NOW() - INTERVAL '2 hours'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%taylor%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  NULL,
  'routine_visit',
  'Pre-operative clearance for gallbladder surgery',
  'Patient scheduled for laparoscopic cholecystectomy next week. History of gallstones with recurrent biliary colic. Generally healthy, no significant medical history. Denies chest pain, shortness of breath, or exercise intolerance. No known drug allergies. Takes multivitamin daily, no prescription medications.',
  'Vital Signs: BP 126/78 mmHg, HR 72 bpm, RR 16, Temp 98.6°F, Weight 142 lbs, Height 5''4". General: Well-appearing female in no acute distress. Cardiovascular: Regular rate and rhythm, no murmurs. Pulmonary: Clear to auscultation bilaterally. Recent labs: CBC, CMP, PT/INR all within normal limits. EKG: Normal sinus rhythm.',
  'Healthy 35-year-old female cleared for elective laparoscopic cholecystectomy. Low perioperative risk.',
  '1. Cleared for surgery - ASA Class I\n2. No additional cardiac or pulmonary testing needed\n3. NPO after midnight before surgery\n4. Continue multivitamin until day of surgery\n5. Post-operative follow-up with surgeon as scheduled\n6. No restrictions on activity until surgery',
  NOW() - INTERVAL '1 week',
  NOW() - INTERVAL '1 week'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%anderson%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  NULL,
  'Anxiety Depression Follow-up',
  'Type 2 diabetes management and foot care',
  'Patient with 8-year history of type 2 diabetes returns for routine follow-up. Currently on metformin 1000mg twice daily and insulin glargine 24 units at bedtime. Home glucose readings range 120-180 mg/dL fasting. Reports good adherence to diabetic diet and checking feet daily. Denies symptoms of hypoglycemia or hyperglycemia. Sees podiatrist every 3 months.',
  'Vital Signs: BP 128/82 mmHg, HR 76 bpm, Weight 195 lbs (stable). Feet: No ulcers, calluses, or deformities noted. Sensation intact to monofilament testing. Pulses palpable. Recent HbA1c: 7.2% (goal <7%). Microalbumin: 15 mg/g creatinine (normal). Dilated eye exam last month: no retinopathy.',
  'Type 2 diabetes mellitus with good overall control. HbA1c slightly above goal. No evidence of diabetic complications.',
  '1. Continue current insulin and metformin regimen\n2. Consider increasing insulin glargine to 26 units if morning glucose >130 mg/dL\n3. Reinforce carbohydrate counting and portion control\n4. Continue daily foot inspections and regular podiatry visits\n5. Annual ophthalmology exam due in 11 months\n6. Order lipid panel and microalbumin next visit\n7. Return in 3 months',
  NOW() - INTERVAL '8 days',
  NOW() - INTERVAL '8 days'
);