-- Sample Appointments with Realistic US Healthcare Data
INSERT INTO appointments (id, patient_id, practitioner_id, title, description, appointment_date, duration, type, status, notes, created_at, updated_at) VALUES
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%johnson%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'Annual Physical Examination',
  'Comprehensive annual physical exam including preventive care screening, medication review, and health maintenance counseling.',
  '2025-08-15 09:00:00'::timestamp,
  60,
  'routine',
  'confirmed',
  'Patient requested morning appointment. Fasting labs needed - draw at 8:30 AM before appointment.',
  NOW() - INTERVAL '2 weeks',
  NOW() - INTERVAL '2 weeks'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%smith%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'Follow-up: Upper Respiratory Infection',
  'Follow-up visit for upper respiratory infection treatment progress and symptom resolution.',
  '2025-08-02 14:30:00'::timestamp,
  30,
  'follow_up',
  'completed',
  'Patient reported significant improvement. Cleared to return to work.',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '3 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%williams%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'Mental Health Follow-up',
  'Psychiatric follow-up for anxiety and depression management. Review medication effectiveness and side effects.',
  '2025-08-20'::date,
  '11:00:00'::time,
  '11:30:00'::time,
  'confirmed',
  'follow_up',
  'Bring completed PHQ-9 and GAD-7 questionnaires. Continue CBT sessions.',
  NOW() - INTERVAL '1 week',
  NOW() - INTERVAL '1 week'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%brown%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'Back Pain Evaluation',
  'Orthopedic consultation for chronic lower back pain assessment and treatment planning.',
  '2025-08-25'::date,
  '15:00:00'::time,
  '16:00:00'::time,
  'confirmed',
  'consultation',
  'Bring MRI lumbar spine results and physical therapy progress notes.',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '5 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%davis%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'Well Child Check - 6 Years',
  'Annual well-child examination including growth assessment, developmental screening, and immunizations.',
  '2025-09-10'::date,
  '10:00:00'::time,
  '10:30:00'::time,
  'scheduled',
  'routine',
  'School physical form needed. Kindergarten vaccine requirements to be reviewed.',
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '10 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%miller%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'UTI Follow-up',
  'Follow-up appointment to ensure urinary tract infection has resolved and review preventive measures.',
  '2025-08-08'::date,
  '16:00:00'::time,
  '16:15:00'::time,
  'scheduled',
  'follow_up',
  'Urinalysis to be done 15 minutes before appointment. Patient education on prevention.',
  NOW() - INTERVAL '6 days',
  NOW() - INTERVAL '6 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%wilson%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'Hypertension Management',
  'Blood pressure monitoring and medication adjustment for hypertension control.',
  '2025-08-30'::date,
  '13:00:00'::time,
  '13:30:00'::time,
  'scheduled',
  'follow_up',
  'Bring home BP log. Lipid panel results to be reviewed.',
  NOW() - INTERVAL '12 days',
  NOW() - INTERVAL '12 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%moore%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'Migraine Consultation',
  'Neurology consultation for recurrent migraine headaches and preventive treatment options.',
  '2025-09-05'::date,
  '14:00:00'::time,
  '15:00:00'::time,
  'scheduled',
  'consultation',
  'Bring headache diary and list of current triggers. MRI brain may be ordered.',
  NOW() - INTERVAL '8 days',
  NOW() - INTERVAL '8 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%taylor%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'Post-Surgical Follow-up',
  'Post-operative follow-up after laparoscopic cholecystectomy to assess healing and recovery.',
  '2025-08-12'::date,
  '11:30:00'::time,
  '12:00:00'::time,
  'completed',
  'follow_up',
  'Surgical sites healing well. Patient cleared for normal activities.',
  NOW() - INTERVAL '4 days',
  NOW() - INTERVAL '4 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%anderson%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'Diabetes Management',
  'Quarterly diabetes follow-up for blood sugar monitoring, medication adjustment, and complication screening.',
  '2025-09-15'::date,
  '08:30:00'::time,
  '09:30:00'::time,
  'scheduled',
  'routine',
  'Fasting required. HbA1c and comprehensive metabolic panel to be drawn. Foot exam included.',
  NOW() - INTERVAL '15 days',
  NOW() - INTERVAL '15 days'
);